-- Conectado con el Usuario: MACEVEDO_REPORT
-- REQUERIMIENTO 2

-- Creando la vista con restriccion de solo lectura
CREATE OR REPLACE VIEW VW_PRODUCTO_BOLETA AS
SELECT 
    p.CODPRODUCTO CODIGO_PRODUCTO,
    p.DESCRIPCION DESCRIPCION_PRODUCTO,
    p.CODPAIS CODIGO_PAIS,
    pa.NOMPAIS NOMBRE_PAIS,
    p.CODUNIDAD CODIGO_UNIDAD,
    um.DESCRIPCION DESCRIPCION_UNIDAD,
    COUNT(DISTINCT db.NUMBOLETA) CANTIDAD_BOLETA,
    NVL(SUM(db.CANTIDAD), 0) CANTIDAD_PROD_COMPRADOS,
    p.TOTALSTOCK STOCK_ACTUAL,
    TO_CHAR(p.VALORCOMPRAPESO, '$99G999G999')VALOR_COMPRA,
    TO_CHAR(ROUND(p.VALORCOMPRAPESO * 1.10), '$99G999G999')NUEVO_VALOR_COMPRA
FROM PROD_REP p
JOIN PAIS_REP pa ON p.CODPAIS = pa.CODPAIS
JOIN UMEDIDA_REP um ON p.CODUNIDAD = um.CODUNIDAD
LEFT JOIN DETBOL_REP db ON p.CODPRODUCTO = db.CODPRODUCTO
WHERE p.TOTALSTOCK > 10
GROUP BY 
    p.CODPRODUCTO, 
    p.DESCRIPCION, 
    p.CODPAIS, 
    pa.NOMPAIS, 
    p.CODUNIDAD, 
    um.DESCRIPCION, 
    p.TOTALSTOCK, 
    p.VALORCOMPRAPESO
WITH READ ONLY;

-- Consulta para mostrar el informe
SELECT * FROM VW_PRODUCTO_BOLETA;