-- Creamos los roles para agrupar los permisos (Req 2)
CREATE ROLE ROL_DUENO_FA;
CREATE ROLE ROL_DESARROLLADOR_FA;

-- Le damos los permisos de sistema a los roles
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE ANY INDEX TO ROL_DUENO_FA;
GRANT CREATE SESSION TO ROL_DESARROLLADOR_FA;
GRANT CREATE VIEW TO ROL_DESARROLLADOR_FA;

-- (Si esta de abajo te sigue dando error ORA-01031, borrala nomas, el examen solo usa CREATE VIEW normal)
GRANT CREATE MATERIALIZED VIEW TO ROL_DESARROLLADOR_FA;

-- Creamos los usuarios asignando tu apellido para que no choque con otros
CREATE USER BDY1102_ET_FA_MACEVEDO IDENTIFIED BY "Base20262026";
CREATE USER BDY1102_ET_FA_DES_MACEVEDO IDENTIFIED BY "Base20262026";

-- Asignamos los roles a cada usuario y les damos almacenamiento ilimitado
GRANT ROL_DUENO_FA TO BDY1102_ET_FA_MACEVEDO;
ALTER USER BDY1102_ET_FA_MACEVEDO QUOTA UNLIMITED ON USERS;

GRANT ROL_DESARROLLADOR_FA TO BDY1102_ET_FA_DES_MACEVEDO;
ALTER USER BDY1102_ET_FA_DES_MACEVEDO QUOTA UNLIMITED ON USERS;

-- Permiso extra necesario para que el desarrollador pueda usar TRUNCATE en el PL/SQL
GRANT DROP ANY TABLE TO BDY1102_ET_FA_DES_MACEVEDO;