-- Conectado con el Usuario: MACEVEDO "MarianoA"
-- REQUERIMIENTO 0

-- 1. Creacion de los usuarios
CREATE USER MACEVEDO_ADM IDENTIFIED BY "Base20262026" DEFAULT TABLESPACE DATA;
CREATE USER MACEVEDO_REPORT IDENTIFIED BY "Base20262026" DEFAULT TABLESPACE DATA;
CREATE USER MACEVEDO_EXTERNO IDENTIFIED BY "Base20262026" DEFAULT TABLESPACE DATA;

-- 2. Creacion de Roles
CREATE ROLE ROL_MACEVEDO_ADMIN;
CREATE ROLE ROL_MACEVEDO_REPORTES;

-- 3. Asignacion de privilegios de sistema a los Roles
-- ROL_MACEVEDO_ADMIN: crear sesion, crear/eliminar/actualizar tablas, crear secuencias, crear vistas materializadas e indices
GRANT CREATE SESSION TO ROL_MACEVEDO_ADMIN;
GRANT CREATE TABLE, DROP ANY TABLE, ALTER ANY TABLE TO ROL_MACEVEDO_ADMIN;
GRANT CREATE SEQUENCE TO ROL_MACEVEDO_ADMIN;
GRANT CREATE MATERIALIZED VIEW TO ROL_MACEVEDO_ADMIN;
GRANT CREATE ANY INDEX TO ROL_MACEVEDO_ADMIN;

-- ROL_MACEVEDO_REPORTES: crear sesion, crear vistas y crear procedimientos almacenados
GRANT CREATE SESSION TO ROL_MACEVEDO_REPORTES;
GRANT CREATE VIEW TO ROL_MACEVEDO_REPORTES;
GRANT CREATE PROCEDURE TO ROL_MACEVEDO_REPORTES;

-- 4. Asignacion de Roles a los usuarios correspondientes
GRANT ROL_MACEVEDO_ADMIN TO MACEVEDO_ADM;
GRANT ROL_MACEVEDO_REPORTES TO MACEVEDO_REPORT;

-- 5. Privilegios de sistema adicionales y cuotas
-- Segun la tabla de "Acciones" el ADM tambien debe crear sinonimos publicos y vistas
GRANT CREATE PUBLIC SYNONYM, CREATE VIEW TO MACEVEDO_ADM;

-- El usuario externo solo necesita conexion
GRANT CREATE SESSION TO MACEVEDO_EXTERNO;

-- Cuotas de almacenamiento
ALTER USER MACEVEDO_ADM QUOTA UNLIMITED ON DATA;
ALTER USER MACEVEDO_REPORT QUOTA UNLIMITED ON DATA;