-- Conectado con el Usuario: MACEVEDO_ADM "ADM"

-- Otorgando permisos de selecct a REPORT
GRANT SELECT ON PRODUCTO TO MACEVEDO_REPORT;
GRANT SELECT ON PAIS TO MACEVEDO_REPORT;
GRANT SELECT ON UNIDAD_MEDIDA TO MACEVEDO_REPORT;
GRANT SELECT ON DETALLE_BOLETA TO MACEVEDO_REPORT;


-- Creando sinonimos publicoS que faltaban para poder llamarlos directamente
CREATE OR REPLACE PUBLIC SYNONYM PROD_REP FOR PRODUCTO;
CREATE OR REPLACE PUBLIC SYNONYM PAIS_REP FOR PAIS;
CREATE OR REPLACE PUBLIC SYNONYM UMEDIDA_REP FOR UNIDAD_MEDIDA;
CREATE OR REPLACE PUBLIC SYNONYM DETBOL_REP FOR DETALLE_BOLETA;