CREATE ROLE ROL_DEV_MACEVEDO;

-- Privilegios para el rol
GRANT CREATE PROCEDURE,
    CREATE TRIGGER,
    CREATE ANY INDEX TO ROL_DEV_MACEVEDO;
    
-- Otorgar rol al Desarrollador (MACEVEDO_2)
GRANT ROL_DEV_MACEVEDO TO MACEVEDO_2;


-- Permisos para MACEVEDO_1
-- Permisos básicos de acceso y creación
GRANT CREATE SESSION TO MACEVEDO_1;
GRANT CREATE TABLE TO MACEVEDO_1;
GRANT CREATE SEQUENCE TO MACEVEDO_1;
GRANT CREATE VIEW TO MACEVEDO_1;
GRANT CREATE PROCEDURE TO MACEVEDO_1;
GRANT CREATE TRIGGER TO MACEVEDO_1;

-- Permiso para crear Sinónimos Públicos (Fundamental para el Requerimiento 3)
GRANT CREATE PUBLIC SYNONYM TO MACEVEDO_1;

-- Permiso para crear sus propios índices
GRANT CREATE ANY INDEX TO MACEVEDO_1;

--PROBANDO
ALTER USER MARIANO_1 QUOTA UNLIMITED ON DATA; 
GRANT UNLIMITED TABLESPACE TO MACEVEDO_1;

ALTER USER MACEVEDO_1 QUOTA UNLIMITED ON DATA; 
GRANT UNLIMITED TABLESPACE TO MACEVEDO_1;