-- REQUERIMIENTO 2
SELECT
    m.NOMBRE_MARCA MARCA_CAMION,
    tc.NOMBRE_TIPO_CAMION TIPO_CAMION,
    TO_CHAR(ac.FECHA_INI_ARRIENDO, 'YYYY') AÑO_ARRIENDO,
    COUNT(ac.ID_ARRIENDO) CANTIDAD_ARRIENDOS
FROM ARRIENDO_CAMION ac
    JOIN CAMION c ON (ac.NRO_PATENTE = c.NRO_PATENTE)
    JOIN MARCA m ON (c.ID_MARCA = m.ID_MARCA)
    JOIN TIPO_CAMION tc ON (c.ID_TIPO_CAMION = tc.ID_TIPO_CAMION)
WHERE ac.FECHA_INI_ARRIENDO >= TO_DATE('01/01/2021', 'DD/MM/YYYY')
GROUP BY m.NOMBRE_MARCA,
         tc.NOMBRE_TIPO_CAMION,
         TO_CHAR(ac.FECHA_INI_ARRIENDO, 'YYYY')
ORDER BY CANTIDAD_ARRIENDOS DESC,
         AÑO_ARRIENDO DESC;