-- 1. Calculando el promedio anual de arriendos para el año actual
SELECT 
    AVG(COUNT(ac.ID_ARRIENDO)) PROMEDIO_ANUAL_ARRIENDOS
FROM ARRIENDO_CAMION ac
WHERE TO_CHAR(ac.FECHA_INI_ARRIENDO, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY')
GROUP BY ac.NUMRUN_CLI;

-- 2. Buscando clientes bajo el promedio para seleccionarlos como bronce
SELECT
    TO_CHAR(SYSDATE, 'YYYY') AÑO_PROCESO,
    cli.PNOMBRE_CLI   || ' ' || 
    cli.SNOMBRE_CLI   || ' ' || 
    cli.APPATERNO_CLI || ' ' || 
    cli.APMATERNO_CLI NOMBRE,
    COUNT(ac.ID_ARRIENDO) TOTAL_ARRIENDOS
FROM CLIENTE cli
LEFT JOIN ARRIENDO_CAMION ac ON cli.NUMRUN_CLI = ac.NUMRUN_CLI
WHERE TO_CHAR(ac.FECHA_INI_ARRIENDO, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY')
GROUP BY cli.PNOMBRE_CLI, cli.SNOMBRE_CLI, cli.APPATERNO_CLI, cli.APMATERNO_CLI
HAVING COUNT(ac.ID_ARRIENDO) < (
    -- Compras anual por cliente
    SELECT AVG(COUNT(ac2.ID_ARRIENDO))
    FROM ARRIENDO_CAMION ac2
    WHERE TO_CHAR(ac2.FECHA_INI_ARRIENDO, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY')
    GROUP BY ac2.NUMRUN_CLI)
ORDER BY cli.APPATERNO_CLI ASC;

-- PENDIENTE
-- INSERT en la tabla CLIENTES_ARRIENDOS_MENOS_PROM
-- UPDATE masivo a categoria 100 (bronce)