-- REQUERIMIENTO 4
CREATE TABLE HIST_ARRIENDO_2024 AS

SELECT
    c.NRO_PATENTE PATENTE_CAMION,
    'Motor: '    || c.MOTOR || 
    ' - Color: ' || c.COLOR || 
    ' - Año: '   || c.ANIO CARACTERISTICAS,
    TO_CHAR(ac.FECHA_INI_ARRIENDO, 'YYYY') AÑO_ARRIENDO,
    SUM(ac.DIAS_SOLICITADOS) TOTAL_DIAS_SOLICITADOS
FROM CAMION c
    JOIN ARRIENDO_CAMION ac ON (c.NRO_PATENTE = ac.NRO_PATENTE)
WHERE TO_CHAR(ac.FECHA_INI_ARRIENDO, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY')-1
GROUP BY c.NRO_PATENTE,
         c.MOTOR,
         c.COLOR,
         c.ANIO,
         TO_CHAR(ac.FECHA_INI_ARRIENDO, 'YYYY')
-- ORDEN PARA SABER CUAL ES EL MAS SOLICITADO ESTO 
-- ES EXTRA PROFE ERA PARA QUE SE VIERA MAS PROFESIONAL
ORDER BY TOTAL_DIAS_SOLICITADOS DESC;
         
DROP TABLE HIST_ARRIENDO_2024;