
--------------------------------------------------------------

-- Conectado con el Usuario: MACEVEDO_ADM
-- REQUERIMIENTO 1: Optimizacion de sentencias SQL

-- 1A Optimizacion para la consulta de DETALLE_BOLETA
CREATE INDEX IDX_DETALLE_BOLETA_OPT ON DETALLE_BOLETA(VUNITARIO, CANTIDAD);

-- 1B Optimizacion para la consulta de VENDEDOR
CREATE INDEX IDX_VENDEDOR_NOMBRE_OPT ON VENDEDOR(NOMBRE);

-- Sinonimos Publicos (para que MACEVEDO_REPORT pueda trabajar facil, buena practica)
CREATE PUBLIC SYNONYM CLIENTE FOR MACEVEDO_ADM.CLIENTE;
CREATE PUBLIC SYNONYM VENDEDOR FOR MACEVEDO_ADM.VENDEDOR;
CREATE PUBLIC SYNONYM PRODUCTO FOR MACEVEDO_ADM.PRODUCTO;
CREATE PUBLIC SYNONYM BOLETA FOR MACEVEDO_ADM.BOLETA;
CREATE PUBLIC SYNONYM DETALLE_BOLETA FOR MACEVEDO_ADM.DETALLE_BOLETA;
CREATE PUBLIC SYNONYM CATEGORIA FOR MACEVEDO_ADM.CATEGORIA;
