SELECT DISTINCT
       SR.ID_SUCURSAL ID_SUCURSAL,
       REGS.NOMBRE_REGION REGION_SUCURSAL,
       TO_CHAR(CLI.NUMRUN,'99G999G999') || '-' || CLI.DVRUN RUN_CLIENTE,
       INITCAP(CLI.PNOMBRE) || ' ' ||
       INITCAP(SUBSTR(CLI.SNOMBRE,1,1)) ||'.'|| ' ' ||
       INITCAP(CLI.APPATERNO) || ' ' ||
       INITCAP(CLI.APMATERNO) NOMBRE_CLIENTE,
       INITCAP(CLI.DIRECCION) DIRECCION,
       PRO.NOMBRE_PROVINCIA PROVINCIA,
       REG.NOMBRE_REGION REGION_CLIENTE
FROM CLIENTE CLI
LEFT JOIN PROVINCIA PRO ON (PRO.COD_PROVINCIA = CLI.COD_PROVINCIA)
JOIN REGION REG ON (REG.COD_REGION = CLI.COD_REGION)
JOIN TARJETA_CLIENTE TC ON (CLI.NUMRUN = TC.NUMRUN)
JOIN TRANSACCION_TARJETA_CLIENTE TTC ON (TC.NRO_TARJETA = TTC.NRO_TARJETA)
JOIN SUCURSAL_RETAIL SR ON (TTC.ID_SUCURSAL = SR.ID_SUCURSAL)
JOIN REGION REGS ON (SR.COD_REGION = REGS.COD_REGION)
ORDER BY REGION_CLIENTE ASC,
         SR.ID_SUCURSAL ASC,
         CLI.APPATERNO ASC;